name: ✨ Feature Request
description: Suggest a new feature or enhancement for PMC
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information about your feature request to help us understand and evaluate it.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: By submitting this feature request, you agree to follow our Code of Conduct
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: I have read the roadmap and documentation
          required: true
        - label: This feature would benefit the broader PMC community
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Core Functionality
        - Search & Filtering
        - User Interface/CLI
        - Performance
        - Integration
        - Documentation
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases where this feature would be helpful
      placeholder: |
        1. When working on...
        2. During the process of...
        3. To accomplish...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Essential for my use case
        - Critical - Blocking my adoption of PMC
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I can provide detailed requirements

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here
